# Generated by Django 6.0 on 2025-12-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_profile_created_at_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma separated skills (e.g. Python, Django, React)', max_length=500),
        ),
    ]
